"""
Example: Running the Complete 3-Node Code Review Agent

This example demonstrates how to use the new 3-node architecture:
  Explorer → Reviewer → Summarizer

Usage:
    python -m code_review_agent.nagent.example_3node \\
        --file output/review-2026-04-02_20-32-14/04_review_prompt_api_routers_webhook_py.md \\
        --repo owner/repo
"""

from pathlib import Path

from code_review_agent.nagent.nrunner import run_review_agent


def example_3node_architecture():
    """Example showing the 3-node architecture in action."""

    # Path to the markdown file generated by review_pipeline.py
    review_context_file = Path(
        "output/review-2026-04-02_20-32-14/04_review_prompt_api_routers_webhook_py.md"
    )

    print("=" * 80)
    print("3-Node Code Review Agent")
    print("=" * 80)
    print()
    print("Architecture:")
    print("  1. Explorer   - Investigates with tools (ReAct loop)")
    print("  2. Reviewer   - Generates issues and positives")
    print("  3. Summarizer - Generates walkthrough")
    print()
    print("=" * 80)

    # Run the agent
    result = run_review_agent(
        review_context_file=review_context_file,
        repo_id="skmabudalam/BugViper",
        model="anthropic/claude-sonnet-4-5",
    )

    # Access results
    print("\n" + "=" * 80)
    print("EXPLORATION PHASE")
    print("=" * 80)
    print(f"Tool rounds: {result['tool_rounds']}")
    print(f"Sources collected: {len(result['sources'])}")
    print(f"Messages: {len(result['messages'])}")

    # Print sources
    if result["sources"]:
        print("\nSources:")
        for source in result["sources"][:5]:  # First 5
            path = source.get("path", "?")
            line = source.get("line_number", "?")
            name = source.get("name", "?")
            typ = source.get("type", "?")
            print(f"  - [{typ}] {name} at {path}:{line}")

    # Print issues
    print("\n" + "=" * 80)
    print("REVIEWER OUTPUT - ISSUES")
    print("=" * 80)
    if result["file_based_issues"]:
        for file_issues in result["file_based_issues"]:
            print(f"\n📄 File: {file_issues['file']}")
            print(f"   Issues: {len(file_issues['issues'])}")
            for i, issue in enumerate(file_issues["issues"], 1):
                print(f"\n   Issue #{i}: [{issue['issue_type']}] {issue['title']}")
                print(f"   Line: {issue['line_start']}")
                print(f"   Confidence: {issue['confidence']}/10")
                print(f"   Description: {issue['description']}")
                print(f"   Suggestion: {issue['suggestion']}")
                if issue.get("code_snippet"):
                    print(f"   Code:\n{issue['code_snippet']}")
    else:
        print("\n✅ No issues found")

    # Print positive findings
    print("\n" + "=" * 80)
    print("REVIEWER OUTPUT - POSITIVE FINDINGS")
    print("=" * 80)
    if result["file_based_positive_findings"]:
        for finding in result["file_based_positive_findings"]:
            print(f"\n✨ File: {finding['file_path']}")
            for i, pos in enumerate(finding["positive_finding"], 1):
                print(f"   {i}. {pos}")
    else:
        print("\n✅ No positive findings documented")

    # Print walkthrough
    print("\n" + "=" * 80)
    print("SUMMARIZER OUTPUT - WALKTHROUGH")
    print("=" * 80)
    if result["file_based_walkthrough"]:
        for walk in result["file_based_walkthrough"]:
            print(f"\n📝 File: {walk['file']}")
            print(f"   Steps: {len(walk['walkthrough_steps'])}")
            for i, step in enumerate(walk["walkthrough_steps"], 1):
                print(f"   {i}. {step}")
    else:
        print("\n✅ No walkthrough generated")

    print("\n" + "=" * 80)
    print("REVIEW COMPLETE")
    print("=" * 80)

    return result


if __name__ == "__main__":
    import logging

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    )

    result = example_3node_architecture()
