"""
Example: Running the Code Review Agent

This example demonstrates how to use the code review agent
to analyze a file review context and generate findings.

Usage:
    python -m code_review_agent.nagent.example \\
        --file output/review-2026-04-02_20-32-14/04_review_prompt_api_routers_webhook_py.md \\
        --repo owner/repo
"""

from pathlib import Path

from code_review_agent.nagent.nrunner import run_review_agent


def example_basic_usage():
    """Basic example: Run agent on a review context file."""

    # Path to the markdown file generated by review_pipeline.py
    review_context_file = Path(
        "output/review-2026-04-02_20-32-14/04_review_prompt_api_routers_webhook_py.md"
    )

    # Run the agent
    result = run_review_agent(
        review_context_file=review_context_file,
        repo_id="skmabudalam/BugViper",  # Optional: scope queries to a repo
        model="openai/gpt-4-turbo",
    )

    # Access results
    print(f"Tool rounds used: {result['tool_rounds']}")
    print(f"Sources collected: {len(result['sources'])}")

    # Print issues
    for file_issues in result["file_based_issues"]:
        print(f"\nFile: {file_issues['file']}")
        for issue in file_issues["issues"]:
            print(f"  - [{issue['issue_type']}] {issue['title']}")
            print(f"    Line: {issue['line_start']}, Confidence: {issue['confidence']}/10")

    # Print positive findings
    for finding in result["file_based_positive_findings"]:
        print(f"\nFile: {finding['file_path']}")
        for pos in finding["positive_finding"]:
            print(f"  + {pos}")

    # Print walkthrough
    for walk in result["file_based_walkthrough"]:
        print(f"\nFile: {walk['file']}")
        for i, step in enumerate(walk["walkthrough_steps"], 1):
            print(f"  {i}. {step}")


def example_with_mock_context():
    """Example with programmatically created context."""

    # Create a simple review context (normally comes from pipeline)
    review_context = """
# Review Agent Prompt: example.py

## File Under Review: example.py

## Raw Unified Diff
```diff
diff --git a/example.py b/example.py
--- a/example.py
+++ b/example.py
@@ -1,5 +1,8 @@
 def calculate_total(items):
-    total = 0
-    for item in items:
-        total += item.price
+    if not items:
+        return 0
+    total = sum(item.price for item in items)
     return total
```

## POST-PR File Content (with line numbers)
```
    1 │ def calculate_total(items):
    2 │     if not items:
    3 │         return 0
    4 │     total = sum(item.price for item in items)
    5 │     return total
```

## Diff Hunk Line Ranges
Lines changed: 1-5
Valid comment lines: [1, 2, 3, 4, 5]

## AST Summary
- Functions: calculate_total (line 1, complexity: 2)
- Imports: None

## Explorer Context
No previous issues for this file.
"""

    # Save to temp file
    temp_file = Path("/tmp/example_review.md")
    temp_file.write_text(review_context)

    # Run agent
    result = run_review_agent(
        review_context_file=temp_file,
        repo_id=None,  # Search across all repos
        model="openai/gpt-4-turbo",
    )

    # Check for issues
    if result["file_based_issues"]:
        print("Issues found:")
        for file_issues in result["file_based_issues"]:
            for issue in file_issues["issues"]:
                print(f"  - {issue['title']} (line {issue['line_start']})")
    else:
        print("No issues found.")

    # Clean up
    temp_file.unlink()


if __name__ == "__main__":
    print("=" * 80)
    print("Example 1: Basic Usage")
    print("=" * 80)
    example_basic_usage()

    print("\n" + "=" * 80)
    print("Example 2: With Mock Context")
    print("=" * 80)
    example_with_mock_context()
